# Настройки веб-интерфейса FPTN
# Автор: Antigravity

server.modules += ( "mod_cgi" )

$HTTP["url"] =~ "^/fptn/" {
    cgi.assign = ( ".php" => "/opt/bin/php-cgi" )
    static-file.exclude-extensions += ( ".php" )
}
