# Настройки веб-интерфейса FPTN
# Автор: Antigravity

server.modules += ( "mod_cgi", "mod_redirect" )

$HTTP["url"] == "/fptn" {
    url.redirect = ( "^/fptn$" => "/fptn/" )
}

$HTTP["url"] =~ "^/fptn/" {
    cgi.assign = ( ".php" => "/opt/bin/php-cgi" )
    static-file.exclude-extensions += ( ".php" )
}
