#!/bin/sh

ENABLED=no
PROCS=fptn-client-cli
PROC=/opt/bin/fptn-client-cli
DESC="fptn-client"
CONF=/opt/etc/fptn-client.conf

if [ -f "$CONF" ]; then
    . "$CONF"
fi

if [ "$ENABLED" != "yes" ]; then
    exit 0
fi

if [ -z "$TOKEN" ]; then
    echo "FPTN token is empty in $CONF"
    exit 1
fi

IFNAME="${TUN_INTERFACE:-opkgtun1}"
ARGS="--access-token ${TOKEN} --tun-interface-name ${IFNAME} --disable-routing"

if [ -n "$PREFERRED_SERVER" ]; then
    ARGS="${ARGS} --preferred-server ${PREFERRED_SERVER}"
fi

PRECMD=""
PREARGS=""
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
